#include<bits/stdc++.h>
using namespace std;
int k,a[100],sums[1000000];
int main ()
{
    int n;
    cin>>n;
    for(int i=0; i<n; i++) cin>>a[i];
    sums[k]=a[0];
    k++;
    for(int i=1;i<n;i++)
    {
        int p=k;
     for(int j=0;j<p;j++)
        {
            sums[k]=sums[j]+a[i];
            k++;
        }

     sums[k]=a[i];
     k++;
    }
    for(int i=0;i<k;i++) cout<<sums[i]<<" ";
    cout<<endl;
    return 0;
} 
